export const FETCH_RECOMMENDATION_LIST = 'FETCH_RECOMMENDATION_LIST';

export const FETCH_TOP_FREE_LIST = 'FETCH_TOP_FREE_LIST' ;
export const FETCH_RECOMMENDATION_LIST_FAIL = 'FETCH_RECOMMENDATION_LIST_FAIL' ;
export const FETCH_TOP_FREE_LIST_FAIL = 'FETCH_TOP_FREE_LIST_FAIL' ;
export const FETCH_RECOMMENDATION_LIST_SUCCESS = 'FETCH_RECOMMENDATION_LIST_SUCCESS' ;
export const FETCH_TOP_FREE_LIST_SUCCESS = 'FETCH_TOP_FREE_LIST_SUCCESS' ;
export const SHOW_MORE = 'SHOW_MORE' ;
export const SEARCH_TOP_FREE ='SEARCH_TOP_FREE';
export const UPDATE_RANKING_INFO = 'UPDATE_RANKING_INFO';
export const UPDATE_RANKING_INFO_START = 'UPDATE_RANKING_INFO_START';